config/routes.rb
Rails.application.routes.draw do

  namespace :moderation, :module => nil do
    resources :content_flags do
      member do
        put :resolve
        put :unresolve
      end
      collection do
        get :inbox
        get :resolved
      end
    end
    resources :content_flaggings
    resources :content_flag_types

  end
  get '/moderation(/home)', :to => 'content_flags#index', :as => 'moderation'

  get ":attachable_type/:attachable_id/content_flaggings/new", :to => 'content_flaggings#new'

end

app/models/content_flagging.rb
class ContentFlagging < ActiveRecord::Base

  belongs_to :user
  belongs_to :content_flag
  belongs_to :content_flag_type
  belongs_to :flagger, :class_name => "User", :foreign_key => "user_id"

  delegate :attachable, :has_attachable?, :to => :content_flag

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :allow_blank => true
  validates_presence_of :content_flag_type_id, :message => "please select a reason why you are reporting this content"
  validates_presence_of :content_flag

  # for spam prevention
  attr_accessor :comment
  attr_writer :attachable_type, :attachable_id, :url
  validates_length_of :comment, :maximum => 0, :allow_nil => true, :message => "must be blank"

  before_create :create_content_flag_fields_and_unresolve
  before_validation :build_content_flag, :on => :create
  after_save :remove_post_or_comment_if_needed
  after_create :send_email

  scope :created_at_greater_than, -> (date) { where('content_flaggings.created_at > ?', date) }
  scope :from_today, ->  { where('content_flaggings.created_at > ?', Date.today) }
  scope :from_different_people, -> { group("content_flaggings.ip_address, content_flaggings.user_id") }

  class << self
    def last_month
      date = 27.days.ago.to_date
      by_flag_type = find(:all, :select => "count(*) AS count, content_flag_type_id, EXTRACT(day from created_at) AS day", :group => "content_flag_type_id, created_at").group_by(&:day)

      flag_type_ids = ContentFlagType.all.collect(&:id)
      flagging_data_sets = flag_type_ids.map{|i| []}

      days = []
      while date <= Date.today
        res = {}
        if day_res = by_flag_type[date.day]
          day_res.map{|r| res[r.content_flag_type_id] = r.count}
        end
        flag_type_ids.each_with_index{|fti, idx| flagging_data_sets[idx] << (res[fti] || 0).to_i}
        days << date.day.to_s
        date += 1.day
      end
      return days, flagging_data_sets
    end

    def last_month_max
      res = created_at_greater_than(27.days.ago.to_date).count(:group => "EXTRACT(day from created_at)", :order => "count_all DESC")
      res.blank? ? 10 : res.to_a[0][1]
    end

    def flag_type_counts
      ret = []
      res = ContentFlagging.group(:content_flag_type_id).count
      ContentFlagType.all.each do |ft|
        ret << (res[ft.id] || 0)
      end
      ret
    end

  end

  def attachable_type
    @attachable_type.try(:camelize) || content_flag.try(:attachable_type)
  end

  def attachable_id
    @attachable_id || content_flag.try(:attachable_id)
  end

  def url
    @url || content_flag.try(:url)
  end

  private
  def build_content_flag
    if !attachable_type.blank? && !attachable_id.blank?
      self.content_flag ||= ContentFlag.find_or_initialize_by(attachable_type: attachable_type, attachable_id:attachable_id)
      self.content_flag.user = attachable.user
    elsif !url.blank?
      self.content_flag ||= ContentFlag.find_or_initialize_by_url(url)
    end
  end

  def create_content_flag_fields_and_unresolve
    if has_attachable?
      attachable.class.columns.collect{|col|col.name if ([:text, :string].include?(col.type) && !col.name.match(/type$/))}.compact.each do |attribute|
        content_flag.create_content_flag_field_if_changed(attribute, attachable.send(attribute))
      end
      if attachable.respond_to?(:user_id) && attachable.user_id
        content_flag.create_content_flag_field_if_changed("user_id", attachable.user_id)
      end
    end
    content_flag.unresolve! if content_flag.resolved?
  end

  def remove_post_or_comment_if_needed
    if attachable && (attachable.is_a?(Post) || attachable.is_a?(Comment))
      if !attachable.removed? && attachable.content_flaggings.select("content_flaggings.user_id").where("content_flaggings.user_id IS NOT NULL AND content_flaggings.user_id != ?",User.elephant.id).group("content_flaggings.user_id").to_a.size >= 3
        attachable.update_attribute(:removed, true)
        if Setting.get("AUTO_SUSPENSION") && attachable.user.role.nil?
          if attachable.user.posts.where("removed = true AND updated_at > ?", Setting.get("AUTO_SUSPENSION_FROM")).count >= Setting.get("AUTO_SUSPENSION_THRESHOLD")
            attachable.user.update(auto_suspended_at: DateTime.now, suspended: true, suspended_message: Snippet.find_by(slug: :auto_suspension_message).to_s)
          end
        end
      end
    end
  end

  def send_email
    ContentFlaggingNotifier.delay.content_flagging_notification(self)
  end

end

app/controllers/content_flaggings_controller.rb
class ContentFlaggingsController < ModerationBaseController

  def new
    @content_flagging = ContentFlagging.new(:attachable_type => params[:attachable_type], :attachable_id => params[:attachable_id], :url => params[:url])
    render :partial => "content_flaggings/form", :locals => {:content_flagging => @content_flagging}
  end

  def create
    @content_flagging = ContentFlagging.new(content_flagging_params.merge(:user => current_user, :ip_address => request.remote_ip))
    @success = @content_flagging.save
    respond_to do |format|
      format.js
    end

  end

  private

  def content_flagging_params
    params.require(:content_flagging).permit(:attachable_type, :attachable_id, :url, :message, :email, :content_flag_type_id)
  end

end

app/views/content_flaggings/_form.haml
#content_flag_box

  :javascript
    $(document).ready(function() {
      $('#content_flag_box form').bind("ajax:beforeSend", function(event) {
        $('#content_flagging_submit').hide(0, function() {
          $('#content_flagging_form_loader').show();     
        });
      });
    });
    
  #content_flag_form_wrapper
    %h3 Inappropriate Content
    %p
      Use the box below to provide details about the inappropriate content you have found. An email will be sent to the website administrator.
    =semantic_form_for(content_flagging, :url => moderation_content_flaggings_path, :remote => true) do |form|
      =form.input :attachable_type, :as => :hidden
      =form.input :attachable_id, :as => :hidden
      =form.input :url, :as => :hidden
      =form.input :content_flag_type, :label => "Why is this inappropriate?", :prompt => "Please select..."
      =form.input :message, :as => :text, :input_html => {:rows => 4, :class => 'span5'}, :label => "Please give some details here"
      =form.input :email, :label => "If you would like to be contacted, please enter your email address:"
      =form.buttons do
        =form.commit_button "Report"
      #content_flagging_form_loader{:style => "display:none"}
        =moderation_image_tag("ajax_loader_light.gif")

app/views/content_flaggings/_form.html.haml
#content_flag_box
  #content_flag_form_wrapper
    %h3 Inappropriate Content
    %p
      Use the box below to provide details about the inappropriate content you have
      %br
      found. An email will be sent to the website administrator.
    -semantic_remote_form_for(content_flagging) do |form|
      -form.inputs do
        =form.input :content_flag_id, :as => :hidden
        =form.input :flagged_by_human, :as => :hidden, :value => true
        =form.input :content_flag_type, :prompt => "Why is this inappropriate?", :label => false
        =form.input :message, :label => "Please give some details here", :input_html => {:cols => 69, :rows => 5}
        =form.input :email, :label => "If you would like to be contacted, please enter your email address:"
        =form.input :comment, :label => "Please leave the following field blank", :wrapper_html => {:style => "width: 1px; height: 1px; overflow: hidden;"}
      -form.buttons do
        =form.commit_button "Report"

app/views/content_flaggings/_success.haml
%h3 Inappropriate content reported

%p.moderation_success_message
  Thanks for reporting this content as inappropriate. The system administrators have been notified. We apologise for any offensive material posted.

%p.moderation_close_link
  -# =link_to_function("Close", "$.fancybox.close()", :class => "bttn_l")
  =link_to "Close", "#", onclick: "$.fancybox.close()", :class => "bttn_l"

app/views/content_flaggings/_success.html.haml
%h3 Inappropriate content reported

%p Thanks for reporting this content as inappropriate. The system administrators have been notified. We apologise for any offensive material posted.
  
%p=link_to_function("Close", "$.fancybox.close()", :class => "bttn_l")

app/views/content_flaggings/create.js.erb
<% if @success %>
  $('#content_flag_form_wrapper').replaceWith('<%= escape_javascript(render("content_flaggings/success")) %>');
<% else %>
  $('#content_flag_box').replaceWith('<%= escape_javascript(render("content_flaggings/form", :content_flagging => @content_flagging)) %>');
<% end %>