config/routes.rb
Rails.application.routes.draw do

  namespace :moderation, :module => nil do
    resources :content_flags do
      member do
        put :resolve
        put :unresolve
      end
      collection do
        get :inbox
        get :resolved
      end
    end
    resources :content_flaggings
    resources :content_flag_types

  end
  get '/moderation(/home)', :to => 'content_flags#index', :as => 'moderation'

  get ":attachable_type/:attachable_id/content_flaggings/new", :to => 'content_flaggings#new'

end

app/models/content_flag.rb
require 'iconv'
class ContentFlag < ActiveRecord::Base

  belongs_to :user
  belongs_to :attachable, :polymorphic => true
  belongs_to :resolved_by, :class_name => "User"
  before_create :set_opened_at

  has_many :content_flag_fields, :autosave => true, :dependent => :destroy
  has_many :content_flaggings, :dependent => :destroy
  has_many :content_flag_types, :through => :content_flaggings

  validates_presence_of :url, :unless => :has_attachable?

  scope :latest, -> { select("content_flags.*, COUNT(content_flaggings.id) AS flagging_count").joins(:content_flaggings).group("content_flags.id").order("flagging_count DESC, content_flags.opened_at DESC") }
  scope :unresolved, -> { joins(:content_flaggings).where(resolved_at: nil) }
  scope :resolved, -> { where("content_flags.resolved_at IS NOT NULL") }
  scope :for_type, lambda {|flag_type| {:select => "DISTINCT content_flags.*", :joins => :content_flaggings, :conditions => ["content_flaggings.content_flag_type_id = ?", flag_type.id]}}
  scope :ascend_by_resolved_at, -> {order("content_flags.resolved_at ASC") }
  scope :descend_by_resolved_at, -> { order("content_flags.resolved_at DESC") }
  scope :not_including, ->(content_flag) { (content_flag.nil? || content_flag.id.nil?) ? all : where("content_flags.id != #{ content_flag.id }")}

  class << self

    def average_response_in_seconds
      resolved.average('EXTRACT(EPOCH FROM (resolved_at - created_at))').to_i
    end

    def average_response
      time = average_response_in_seconds
      return time, "second" if time < 600
      time = time/60
      return time, "minute" if time < 240
      time = time/60
      return time, "hour" if time < 24
      time = time/24
      return time, "day"
    end

    def unresolved_count
      unresolved.count(:id, :distinct => true)
    end

    def search(type, query)
      table = type.constantize.table_name
      ContentFlag.resolved.where(attachable_type: type).
        joins("INNER JOIN #{table} ON content_flags.attachable_id = #{table}.id").
        includes(:content_flaggings, :user, :content_flag_fields).
        where("#{table}.text ILIKE ?", "%#{query}%").limit(100)
    end

    def search_posts(query)
      search('Post', query)
    end

    def search_comments(query)
      search('Comment', query)
    end

    def search_messages(query)
      search('Message', query)
    end

    def search_users(query)
      ContentFlag.resolved.
        joins("INNER JOIN users ON content_flags.user_id = users.id").
        includes(:content_flaggings, :user, :content_flag_fields).
        where("users.nickname ILIKE ?", "%#{query}%").limit(100)
    end

  end

  def create_content_flag_field_if_changed(attribute, value)
    latest_flag = content_flag_fields.name_is(attribute.to_s).latest.first
    if latest_flag.blank?
      content_flag_fields.create(:name => attribute.to_s, :value => value)
    elsif(latest_flag.value != value)
      content_flag_fields.create(:name => attribute.to_s, :value => value)
    end
  end

  def has_attachable?
    attachable_id.present?
  end

  def history(field = nil)
    h = []
    h += content_flaggings
    if field && text_field
      h += content_flag_fields.name_is(text_field.name).name_is_not("user_id")
    else
      h += content_flag_fields.name_is_not("user_id")
    end
    h.sort{|x,y| y.created_at <=> x.created_at}
  end

  def user_full_name
    user.nil? ? nil : user.full_name
  end

  def name
    if user
      has_attachable? ? "#{user.full_name}'s #{attachable_type.downcase}" : user.full_name
    elsif has_attachable?
      "A #{attachable_type.downcase}"
    else
      "#{APP_CONFIG['site_url']}#{url.to_s}"
    end
  end
  alias_method :to_s, :name

  def next(options = {})
    if options[:menu_item]=="resolved"
      return ContentFlag.resolved.descend_by_resolved_at.find(:first, :conditions => ["content_flags.resolved_at < ?", resolved_at])
    end
    content_flag_type = ContentFlagType.find_by_id(options[:content_flag_type_id])
    next_content_flags = content_flag_type.nil? ? ContentFlag : content_flag_type.content_flags
    next_content_flags.unresolved.where("content_flags.created_at < ?", self.created_at).not_including(self).order(created_at: :desc).first
  end

  def prev(options = {})
    if options[:menu_item]=="resolved"
      return ContentFlag.resolved.ascend_by_resolved_at.find(:first, :conditions => ["content_flags.resolved_at > ?", resolved_at])
    end
    content_flag_type = ContentFlagType.find_by_id(options[:content_flag_type_id])
    prev_content_flags = content_flag_type.nil? ? ContentFlag : content_flag_type.content_flags
    prev_content_flags.unresolved.where("content_flags.created_at > ?", self.created_at).not_including(self).order(created_at: :asc).first
  end

  def text_field
    if has_attachable?
      text_fields = content_flag_fields.reject{|f| ["user_id","attachable_type"].include?(f.name)}
      if !text_fields.blank?
        if !(t = text_fields.select{|f| f.name == "text"}).blank?
          t.first
        elsif !(t = text_fields.select{|f| f.name == "description"}).blank?
          t.first
        else
          text_fields.first
        end
      end
    end
  end

  def current_text
    if text_field
      return "** The original #{attachable_type.downcase} has been deleted **" unless attachable
      attachable.send(text_field.name)
    end
  end

  def resolve!(user)
    return nil if user.nil?
    self.update_attributes(:resolved_by => user, :resolved_at => Time.now)
  end

  def unresolve!
    self.update_attributes(:resolved_by => nil, :resolved_at => nil, :opened_at => Time.now)
  end

  def resolved
    !resolved_at.blank?
  end
  alias_method :resolved?, :resolved

  def resolved_at_string
    return "" if resolved_at.nil?
    time_str = resolved_at.year == Time.now.year ? "%e %b at %H:%M" : "%e %b %y at %H:%M"
    resolved_at.strftime(time_str)
  end

  def text
    text_field ? text_field.value : nil
  end

  private
  def set_opened_at
    self.opened_at = Time.now
  end

end

app/models/content_flag_type.rb
class ContentFlagType < ActiveRecord::Base
  
  has_many :content_flaggings, :dependent => :destroy
  
  validates_presence_of :name, :color

  scope :ascend_by_name, -> { order("content_flag_types.name ASC") }

  def content_flags
    ContentFlag.for_type(self)
  end
  
  def unresolved_content_flag_count
    content_flags.unresolved.count(:id, :distinct => true)
  end
  
  def hex_color
    color[1..6]
  end

  def to_s
    name
  end
    
end

app/controllers/content_flags_controller.rb
class ContentFlagsController < ModerationBaseController

  admin_only :index, :inbox, :resolve, :unresolve, :resolved, :show

  def new
    @content_flag = ContentFlag.new(:url => params[:url], :attachable => get_attachable)
    render :partial => "content_flags/form", :locals => {:content_flag => @content_flag}
  end

  def create
    @content_flag = ContentFlag.new(params[:content_flag].merge(:user => current_user))
    render :update do |page|
      if @content_flag.save
        page[:content_flag_form_wrapper].replace(render("content_flags/success"))
        page << "$.fancybox.resize();"
      else
        page[:content_flag_box].replace(render("content_flags/form", :content_flag => @content_flag))
      end
    end
  end

  def index
    @dashboard = true
    @flaggings = ContentFlagging.last_month
    set_up_sidebar
    render :template => 'moderation/index'
  end

  def inbox
    @content_flags = ContentFlag.unresolved.latest
    set_up_sidebar
    if request.xhr?
      replace_moderation_content('content_flag_list', :content_flags => @content_flags, :content_flag_types => @content_flag_types, :active_li => "inbox")
    else
      render :template => 'moderation/index'
    end
  end

  def resolve
    @content_flag = ContentFlag.find(params[:id])
    @content_flag.resolve!(current_user)
    @content_flag_type = ContentFlagType.find_by_id(params[:content_flag_type_id])
    if next_content_flag = @content_flag.next(:menu_item => params[:menu_item], :content_flag_type_id => @content_flag_type.try(:id))
      replace_moderation_content('content_flag', :content_flag => next_content_flag)
    elsif @content_flag_type
      replace_moderation_content("content_flags/content_flag_list", :content_flags => @content_flag_type.content_flags.unresolved.latest, :active_li => "content_flag_type_#{@content_flag_type.id}", :active_color => @content_flag_type.color)
    else
      set_up_sidebar
      replace_moderation_content('content_flag_list', :content_flags => ContentFlag.unresolved.latest, :content_flag_types => @content_flag_types, :active_li => "inbox")
    end
  end

  def resolved
    if params[:q].present?
      term = params[:q].strip
      post_flags = ContentFlag.search_posts(term)
      comment_flags = ContentFlag.search_comments(term)
      message_flags = ContentFlag.search_messages(term)
      user_flags = ContentFlag.search_users(term)
      @content_flags = post_flags + comment_flags + message_flags + user_flags
    else
      @content_flags = ContentFlag.resolved.descend_by_resolved_at.paginate(:per_page => 20, :page => params[:page])
    end

    set_up_sidebar
    if request.xhr?
      replace_moderation_content('content_flag_list', :content_flags => @content_flags, :content_flag_types => @content_flag_types, :active_li => "resolved")
    else
      render :template => 'moderation/index'
    end
  end


  def unresolve
    @content_flag = ContentFlag.find(params[:id])
    @content_flag.unresolve!
    replace_moderation_content('content_flag', :content_flag => @content_flag)
  end

  def show
    @content_flag = ContentFlag.find(params[:id])
    @content_flag_type = ContentFlagType.find_by_id(params[:content_flag_type_id])
    if request.xhr?
      replace_moderation_content('content_flag', :content_flag => @content_flag)
    else
      set_up_sidebar
      render :template => 'moderation/index'
    end
  end

  private
  def get_attachable
    return nil if params[:attachable_type].blank? || params[:attachable_id].blank?
    params[:attachable_type].camelize.constantize.find(params[:attachable_id])
  end

end

app/helpers/content_flags_helper.rb
module ContentFlagsHelper

  include YoomeeModeration::ReadMoreTruncate
  
  def comment_url(comment, url_options = {})
    polymorphic_url(comment.commentable, url_options)
  end
  
  def comment_path(comment, url_options = {})
    polymorphic_path(comment.commentable, url_options)
  end
  
  def content_flag_link(*args)
    include_yoomee_fancybox_js
    options = args.extract_options!
    options.reverse_merge!(:text => "Report")
    attachable = args.first
    options[:class] = "content_flag_link yoomee_fancy #{options[:class]}"
    if attachable.nil?
      link_to options.delete(:text), new_moderation_content_flagging_path(:url => options.delete(:url) || request.request_uri), options
    else
      link_to options.delete(:text), "/#{attachable.class.to_s.underscore}/#{attachable.id}/content_flaggings/new", options    
    end
  end
  alias_method :yoomee_flag_link, :content_flag_link
  
  def content_flag_url(content_flag)
    content_flag.attachable.nil? ? content_flag.url : url_for(content_flag.attachable)
  end
  
  def content_flag_type_box(content_flag)
    stripes = ""
    unless (colors = content_flag.content_flag_types.ascend_by_name.uniq.collect(&:color)).blank?
      stripe_width = (20/colors.size.to_f).round
      colors.each do |color|
        width = (color == colors.last ? 20 - stripe_width*(colors.size - 1) : stripe_width)
        stripes << content_tag(:div, "", :class => "stripe", :style => "background-color:#{color};width:#{width}px")
      end
    end
    content_tag(:div, stripes.html_safe, :class => "content_flag_type_box")
  end
  
  def content_flag_type_label(content_flag_type)
    content_tag(:span, content_flag_type, :class => "content_flag_type_label", :style => "background-color:#{content_flag_type.try(:color) || "#2795E4"}")
  end
  
  def include_yoomee_fancybox_js
    return true if @included_ymfb_js
    content_for :head do
      content = javascript_include_tag('/yoomee_moderation/js/jquery.fancybox-1.3.4.pack.js',
                             '/yoomee_moderation/js/jquery.easing-1.3.pack.js',
                             '/yoomee_moderation/js/load_fancybox.js',
                             '/yoomee_moderation/js/jquery.mousewheel-3.0.2.pack.js', 
                              :cache => "yoomee_fancy_box")
    content << "\n#{stylesheet_link_tag('/yoomee_moderation/css/jquery.fancybox.css', '/yoomee_moderation/css/content_flag_box.css')}".html_safe
    end
    @included_ymfb_js = true
  end
  
  def link_to_moderation_content(*args, &block)
    defaults = {:method => :get, :remote => true}
    defaults[:class] = "moderation_content_link #{defaults[:class]}".strip
    if block_given?
      args[1] ||= {}
      args[1].reverse_merge!(defaults)
    else
      args[2] ||= {}
      args[2].reverse_merge!(defaults)
    end
    link_to(*args, &block)
  end
  
  def link_to_every_word(object, attribute)
    returning html = "" do
      html << content_tag(:p, :class => "highlightable"){object.send(attribute).gsub(/[\w]+/,link_to_function('\0', "HighlightText.toggleHighlighted($(this))"))}
      html << render('content_filter_words/multiple_words_form', :uid => "#{object.class.to_s.underscore}_#{object.id}_#{attribute}")
    end
  end
  
  def link_to_url(url, *args, &block)
    options = args.extract_options!.symbolize_keys.reverse_merge!(:http => true, :target => "_blank")
    link_url = url.match(/^.+\:\/\//) ? url : "http://" + url
    url = url.sub(/^https?:\/\//, '') if !options.delete(:http)
    link_to(url, link_url, options, &block)
  end
  
  def moderation_back_link
    if params[:menu_item]=="content_flag_type" && @content_flag_type
      url = moderation_content_flag_type_path(@content_flag_type)
    else
      url = params[:menu_item]=="resolved" ? resolved_moderation_content_flags_path : inbox_moderation_content_flags_path
    end
    link_to_moderation_content("&larr; Back".html_safe, url)
  end
  
  def moderation_image_tag(source, options = {})
    image_tag("/yoomee_moderation/img/#{source}", options)
  end
  
  def moderation_nav_links(content_flag)
    options = {:menu_item => params[:menu_item], :content_flag_type_id => @content_flag_type.try(:id)}
    out = ""
    if prev_content_flag = content_flag.prev(options)
      out << link_to_moderation_content("< Previous", moderation_content_flag_path(prev_content_flag, options))
    else
      out << content_tag(:span, "< Previous")
    end
    if next_content_flag = content_flag.next(options)
      out << link_to_moderation_content("Next >", moderation_content_flag_path(next_content_flag, options))
    else
      out << content_tag(:span, "Next >")
    end
    out.html_safe
  end
  
  def highlight_content_filter_words_javascript
    javascript_tag do
      "var HighlightText = {
        addHighlighted: function(elem) {
          elem.parent().children(':contains(\"' + elem.html() + '\")').addClass('cf_highlighted')
          var form = HighlightText.getForm(elem);
          form.prepend('<input name=\\'content_filter_words[]\\' type=\\'hidden\\' value=\\'' + elem.html() + '\\' />');
          if(form.not(':visible')) { form.show(); }
        },
        clearHighlighting: function(form_id){
          $('#' + form_id + '').prev('p.highlightable').children('.cf_highlighted').removeClass('cf_highlighted');
        },
        getForm: function(elem) {
          return elem.parent().next('form');
        },
        loading: function(elem){
          elem.children('input[type=\"submit\"]').hide();
          elem.children('.ajax_loader').show();
        },
        removeHighlighted: function(elem) {
          elem.parent().children().filter(function(){return $(this).html() == elem.html();}).removeClass('cf_highlighted');
          var form = HighlightText.getForm(elem);
          form.children('input[value=\"' + elem.html() + '\"]').remove();
          if(elem.siblings('.cf_highlighted').length < 1) {
            form.hide();
          }
        },
        toggleHighlighted: function(elem) {
          if(elem.hasClass('cf_highlighted')){
            HighlightText.removeHighlighted(elem);              
          } else {
            HighlightText.addHighlighted(elem);
          }
        }
      }
      "
    end
  end
  
end

app/views/content_flags/_content_flag.haml
:javascript
  $(document).ready(function() {
    YoomeeFancy.init();
  });
  
#content_flag_header
  #left_links
    =moderation_back_link
    - if content_flag.resolved?
      =link_to_moderation_content("Mark as unresolved", unresolve_moderation_content_flag_path(content_flag, :menu_item => "inbox"), :method => :put)
    -else
      =link_to_moderation_content("Mark as resolved", resolve_moderation_content_flag_path(content_flag, :menu_item => params[:menu_item], :content_flag_type_id => @content_flag_type.try(:id)), :method => :put)
  #right_links
    =moderation_nav_links(content_flag)
#content_flag
  %h4#content_flag_title
    ="#{content_flag.name} <span>ref #{content_flag.id}</span>".html_safe
  #flag_edit_links
    -if content_flag.has_attachable?
      =link_to("View in context", content_flag.attachable, :target => "_blank")
    -elsif !content_flag.url.blank?
      =link_to("View in context", content_flag.url, :target => "_blank")
  -if !content_flag.current_text.blank?
    #flag_text
      =read_more_truncate(simple_format("&ldquo;#{content_flag.current_text}&rdquo;"))
  -if false #content_flag.attachable.is_a?(Asset)
    .attachable_preview
      -link_to(content_flag.attachable.url(:user_large), :class => "yoomee_fancy") do
        =uploaded_asset_tag(content_flag.attachable, :medium, content_flag.attachable.description)
  %br
  #flag_history
    %p
      %strong History
    %ul.flag_history
      -if content_flag.resolved?
        %li.resolved_at_item
          Resolved
          ="by #{link_to(content_flag.resolved_by.full_name, content_flag.resolved_by, :target => '_blank')}".html_safe if content_flag.resolved_by
          ="on #{content_flag.resolved_at_string}"
      -content_flag.history(true).each do |item|
        -if item.is_a?(ContentFlagging) || !item.value.blank?
          %li{:id => "#{item.class.to_s.underscore}_#{item.id}", :class => item.class.to_s.underscore}
            -if item.is_a?(ContentFlagging)
              ="Flagged as #{content_flag_type_label(item.content_flag_type)}".html_safe
              ="by #{link_to(item.flagger.full_name, item.flagger, :target => '_blank')}".html_safe if item.flagger
              ="#{time_ago_in_words(item.created_at)} ago"
              -unless (item.message.blank? && item.email.blank?)
                .report
                  -if !item.message.blank?
                    %p
                      %b Their message:
                      =item.message
                  -if !item.email.blank?
                    %p
                      %b Email:
                      =item.email
            -else
              ="Set to &ldquo;#{read_more_truncate(item.value, :length => 50, :simple_format => false)}&rdquo;".html_safe
              ="by #{link_to(content_flag.user.full_name, content_flag.user, :target => '_blank')}".html_safe unless content_flag.user.blank?
              ="#{time_ago_in_words(item.created_at)} ago"

app/views/content_flags/_content_flag.html.haml
#content_flag_header
  #left_links
    =moderation_back_link
    =link_to_moderation_content("Mark as resolved", resolve_content_flag_path(content_flag), :method => :put)
  #right_links
    =moderation_nav_links(content_flag)
#content_flag
  %h4#content_flag_title
    ="#{content_flag.name} <span>ref #{content_flag.id}</span>"
  #flag_edit_links  
    -if content_flag.removable?
      -if content_flag.removed?
        =link_to_moderation_content("Restore", restore_content_flag_path(content_flag, :in_moderation => true), :method => :put)
      -else
        =link_to_moderation_content("Remove", remove_content_flag_path(content_flag, :in_moderation => true), :method => :delete)
    -if content_flag.attachable.is_a?(WallPost)
      =link_to_box("Edit", edit_wall_post_path(content_flag.attachable, :in_moderation => true))
    -if content_flag.has_attachable?
      =link_to("View in context", content_flag.attachable, :target => "_blank")
  #flag_text
    =read_more_truncate(simple_format("&ldquo;#{content_flag.current_text}&rdquo;"))
  %br
  #flag_history
    %p
      %strong History
    %ul.flag_history
      -content_flag.history(true).each do |item|
        %li{:id => "#{item.class.to_s.underscore}_#{item.id}", :class => item.class.to_s.underscore}
          -if item.is_a?(ContentFlagging)
            ="Flagged as #{content_flag_type_label(item.content_flag_type)}"
            ="by #{link_to(item.flagger,item.flagger, :target => '_blank')}" if item.flagger
            ="#{time_ago_in_words(item.created_at)} ago"
            -unless (item.message.blank? && item.email.blank?)
              =link_to_function("View Report", "$(this).parent().toggleClass('open')")
              .report
                -if !item.message.blank?
                  %p
                    %b Message:
                    =item.message
                -if !item.email.blank?
                  %p
                    %b Email:
                    =item.email
          -else
            ="Set to &ldquo;#{read_more_truncate(item.value, :length => 50, :simple_format => false)}&rdquo;"
            ="by #{link_to_self(content_flag.user)}" unless content_flag.user.blank?
            ="#{time_ago_in_words(item.created_at)} ago"

  
-#
  %p=link_to_moderation_content("reload", content_flag_path(content_flag))
  %p=link_to("hard reload", content_flag_path(content_flag))

  %br

  -content_flag.content_flag_fields.each do |flag_field|
    %strong=flag_field.name.titleize
    =link_to_every_word(flag_field, :value)

  %strong Flaggings
  %ul
    -content_flag.content_flaggings.each do |content_flagging|
      %li
        =content_flagging.content_flag_type
        |
        =content_flagging.user
        |
        =content_flagging.message
        |
        ="#{time_ago_in_words(content_flagging.created_at)} ago"
  

app/views/content_flags/_content_flag_list.haml
-if content_flags != []
  #content_flags_list
    -content_flags.each do |content_flag|
      =render 'content_flags/content_flag_list_item', :content_flag => content_flag, :last => (content_flag == content_flags.last)
  -if content_flags.respond_to?(:total_pages)
    #content_flags_pagination=will_paginate(content_flags, :remote => true)
-elsif params[:q].present?
  %p.no_flags No search results found.
-else
  %p.no_flags There are no pending flags.
%br.clear

app/views/content_flags/_content_flag_list_item.haml
-last ||= false
-if @content_flag_type.blank?
  -menu_item = current_page?(resolved_moderation_content_flags_path) ? "resolved" : "inbox"
-else
  -menu_item = "content_flag_type"
=link_to_moderation_content(moderation_content_flag_path(content_flag, :menu_item => menu_item, :content_flag_type_id => @content_flag_type.try(:id))) do
  .content_flag_list_item{:id => "content_flag_#{content_flag.id}", :class => last ? "bottom" : ""}
    =content_flag_type_box(content_flag)
    .title
      =content_flag.id
      %span
        %strong=content_flag.name
        -unless content_flag.text.blank?
          %em=" - " + truncate(strip_tags(content_flag.text).strip, :length => 70 - content_flag.name.length)
    .badges
      .badge.flaggings_count
        =content_flag.content_flaggings.length

app/views/content_flags/_content_flag_list_item.html.haml
-last ||= false
-if @content_flag_type.blank?
  -menu_item = current_page?(resolved_moderation_content_flags_path) ? "resolved" : "inbox"
-else
  -menu_item = "content_flag_type"
-link_to_moderation_content(content_flag_path(content_flag, :menu_item => menu_item, :content_flag_type_id => @content_flag_type.try(:id))) do
  .content_flag_list_item{:id => "content_flag_#{content_flag.id}", :class => last ? "bottom" : ""}
    =content_flag_type_box(content_flag)
    .title
      =content_flag.id
      %span
        %strong=content_flag.name
        -unless content_flag.text.blank?
          %em=" - " + truncate(strip_tags(content_flag.text).strip, 70 - content_flag.name.length)
    .badges
      -if content_flag.auto_removed?
        %span.badge.auto_removed{:title => "Auto removed"} !!
      -if content_flag.flagged_by_system?
        %span.badge.flagged_by_system{:title => "Auto flagged"}
      .badge.flaggings_count
        =content_flag.content_flaggings.count

app/views/content_flags/index.html.haml
-title "Flagged content"
-if !@content_flags.blank?
  #content_flags_list
    -@content_flags.each do |content_flag|
      =render 'content_flag', :content_flag => content_flag
  -if content_flags.respond_to?(:total_pages)
    #content_flags_pagination=will_paginate(@content_flags, :remote => true)
-else
  %p.no_flags There are no pending flags.

app/views/content_flags/show.html.haml
-title @content_flag

-@content_flag.content_flag_fields.each do |flag_field|
  %h4=flag_field.name.titleize
  -unless filtered = YoomeeContentFilter::filter_text(flag_field.value)
    %p
      %strong Filtered Text
    %p=filtered[:starred]
  %p
    %strong Original Text
  =link_to_every_word(flag_field, :value)

app/views/content_flags/update.js.erb
$('#moderation_right_inner').html("<%= escape_javascript(render(@partial_name, @options)) %>");
$('#moderation_sidebar').replaceWith("<%= escape_javascript(render('moderation/sidebar')) %>");
$('#moderation_wrapper').attr('class', "<%= escape_javascript(@wrapper_class) %>");
ModerationContent.finished();
<% if @active_color %>
  $('#moderation_right_col').css('border-color', <%= "'#{active_color}'" %>);
  ModerationContent.finished();
<% end %>