config/routes.rb
Rails.application.routes.draw do

  namespace :moderation, :module => nil do
    resources :content_flags do
      member do
        put :resolve
        put :unresolve
      end
      collection do
        get :inbox
        get :resolved
      end
    end
    resources :content_flaggings
    resources :content_flag_types

  end
  get '/moderation(/home)', :to => 'content_flags#index', :as => 'moderation'

  get ":attachable_type/:attachable_id/content_flaggings/new", :to => 'content_flaggings#new'

end

app/models/content_flagging_notifier.rb
class ContentFlaggingNotifier < ActionMailer::Base

  helper :yoomee_moderation
  
  def content_flagging_notification content_flagging
    @content_flagging = content_flagging
    @attachable = @content_flagging.attachable
    mail(:to => APP_CONFIG['admin_email'], 
         :from => moderation_email,
         :subject => "Inappropriate content has been flagged on #{APP_CONFIG['site_name']}")
  end

  private
  def moderation_email
    return APP_CONFIG['site_email'] if !APP_CONFIG['site_email'].blank?
    res = APP_CONFIG['site_url'].match(/^(https?:\/\/)?(www\.)?([^:]+)/)
    "moderation@#{res[3]}"
  end

end

app/views/content_flagging_notifier/content_flagging_notification.html.haml
%p
  -if @attachable
    = @attachable.respond_to?(:user) && !@attachable.user.nil? ? "#{@attachable.user.full_name}'s" : "A"
    = @attachable.class.to_s.titleize.downcase
  -else
    A page
  has been flagged as inappropriate.
  
-unless @content_flagging.message.blank?
  %p The person who flagged the content left this message:
  %p
    %em= '"' + @content_flagging.message + '"'
    
-unless @content_flagging.email.blank?
  %p
    The person who flagged the content gave their email address:
    %b= @content_flagging.email
  
%p
  You can view the flagged content here:
  -if @attachable
    =link_to_url(polymorphic_url(@attachable))
  -else
    =link_to_url(content_flag_url(@content_flagging.content_flag))

app/views/content_flagging_notifier/content_flagging_notification.text.haml
-first_line = ""
-if @attachable
  -first_line += @attachable.respond_to?(:user) && !@attachable.user.nil? ? "#{@attachable.user.full_name}'s " : "A "
  -first_line += @attachable.class.to_s.titleize.downcase
-else
  -first_line += "A page"
-first_line += " has been flagged as inappropriate."

=first_line

-unless @content_flagging.message.blank?
  The person who flagged the content left this message:
  
  
  = '"' + @content_flagging.message + '"'
  
    
-unless @content_flagging.email.blank?
  ="The person who flagged the content gave their email address: #{@content_flagging.email}"
  
You can view the flagged content here:
-if @attachable
  =polymorphic_url(@attachable)
-else
  =content_flag_url(@content_flagging.content_flag)