config/routes.rb
Rails.application.routes.draw do

  namespace :moderation, :module => nil do
    resources :content_flags do
      member do
        put :resolve
        put :unresolve
      end
      collection do
        get :inbox
        get :resolved
      end
    end
    resources :content_flaggings
    resources :content_flag_types

  end
  get '/moderation(/home)', :to => 'content_flags#index', :as => 'moderation'

  get ":attachable_type/:attachable_id/content_flaggings/new", :to => 'content_flaggings#new'

end

app/views/moderation/_dashboard.haml
#moderation_dashboard
  #latest_activity.dashboard_item
    %h2#latest-activity_title Latest activity
    #graph_axis
      =image_tag(flag_timeline)
  
  #response_time.dashboard_item
    %h2 Average time to resolve
    .average_response
      %span=average_response[0]
      %span.interval=average_response[0] == 1 ? average_response[1] : average_response[1].pluralize
    -#
      %h3.special=average_response[0]
      %span=average_response[0] == 1 ? average_response[1] : average_response[1].pluralize

  #flag_categories_chart.dashboard_item
    %h2 Categories
    #categories_graph
      =image_tag(flag_type_pie)
    %ul#legend.lst
      -ContentFlagType.all.each do |flag_type|
        %li
          %div.legend_color{:style => "background-color:#{flag_type.color}"}
          =flag_type.name
  -if false
    #top_flagged_users.flag_user_list.dashboard_item    
      %h2 Most reported users
      %ul.lst
        -User.most_flagged.limit(5).each do |m|
          %li
            .image
              =user_avatar(m, :size => :tiny)
            %span
              =link_to_self(m, :target => '_blank')
              %br
              ="Reported #{m.flag_count} times"
  #top_flaggers.flag_user_list.dashboard_item    
    %h2 Top reporters
    %ul.lst
      -User.top_flaggers.non_admin.limit(5).each do |m|
        %li
          .image
            =user_avatar(m, :size => :tiny)
          %span
            =link_to(m.full_name, m, :target => '_blank')
            %br
            ="Logged #{m.content_flaggings_count} reports"

app/views/moderation/_sidebar.haml
:javascript
  $(document).ready(function() {
    ModerationSideBar.setup_links();
  });
  
%ul#moderation_sidebar
  %li#inbox{:class => @dashboard ? "active" : ""}
    %span=link_to_moderation_content("Dashboard", moderation_path)
  %li#inbox{:class => (current_page?(:controller => "content_flags", :action => "inbox") || params[:menu_item]=="inbox") ? "active" : ""}
    %span=link_to_moderation_content("Inbox", inbox_moderation_content_flags_path)
    .count=ContentFlag.unresolved_count
  %ul#content_flag_types
    - ContentFlagType.all.each do |content_flag_type|
      %li.content_flag_type{:id => "content_flag_type_#{content_flag_type.id}",:class => @content_flag_type == content_flag_type ? "active" : "", :style => @content_flag_type == content_flag_type ? "background-color:#{content_flag_type.color}" : ""}
        =link_to_moderation_content(truncate(content_flag_type.to_s, :length => 25), moderation_content_flag_type_path(content_flag_type), :html => {:title => content_flag_type})
        .count{:style => "background-color:#{content_flag_type.color}"}
          =content_flag_type.unresolved_content_flag_count
  %li#resolved{:class => (current_page?(resolved_moderation_content_flags_path) || params[:menu_item]=="resolved") ? "active" : ""}
    %span=link_to_moderation_content("Resolved", resolved_moderation_content_flags_path)
  %li#categories{:class => (current_page?(moderation_content_flag_types_path) ? "active" : "")}
    =link_to_moderation_content('Report categories',  moderation_content_flag_types_path)

app/views/moderation/index.html.haml
-content_for :head do
  =#stylesheet_link_tag "/yoomee_moderation/styles.css"
  =#include_yoomee_fancybox_js

-title "Moderation"
#moderation_wrapper
  #moderation_header
    %h1 Moderation tools
  #moderation_left_col
    =render("moderation/sidebar", :content_flag_types => @content_flag_types)
  #moderation_right_col    
    #moderation_right_loader
      =moderation_image_tag("ajax_loader_light.gif")
    #moderation_right_inner
      -if @dashboard
        =render 'moderation/dashboard', :flag_timeline => @flag_timeline, :average_response => @average_response, :flag_type_pie => @flag_type_pie
      -elsif @content_flag && !@content_flag.blank?
        =render 'content_flags/content_flag', :content_flag => @content_flag
      -elsif @content_flags && @content_flags != []
        =render 'content_flags/content_flag_list', :content_flags => @content_flags
      -else
        %p.no_flags There are no pending flags.
  